config/routes.rb
Rails.application.routes.draw do
  

  resources :allowances

  resources :savings

  defaults format: :json do
    constraints format: :json do
      resources :rules

      get "/auth/coinbase", to: "bitcoin_accounts#coinbase_callback"

      mount_devise_token_auth_for 'Account', at: '/auth'
      
      resources :children

      resources :managers

      resources :bitcoin_accounts

      get "/transactions", to: "bitcoin_accounts#transactions"

      post "/payments", to: "bitcoin_accounts#payment"
      
    end
  end
end

app/models/manager.rb
class Manager < ActiveRecord::Base
	has_one :account
	has_many :children
	accepts_nested_attributes_for :account
end

app/controllers/api/managers_controller.rb
module API
  class ManagersController < ApplicationController
    # Add this line when authentication is in place
    #before_action :authenticate_account!

    # GET /managers
    def index
      render json: Manager.all
    end

    # GET /managers/1
    def show
      render json: Manager.find(params[:id])
    end

    # POST /managers
    def create
      manager = Manager.create(manager_params)

      if manager.persisted?
        render json: manager, status: 201
      else
        render json: { errors: manager.errors.full_messages }.to_json, status: 422
      end
    end

    # PATCH/PUT /managers/1
    def update
      manager = Manager.find(params[:id])

      if manager.update(manager_params)
        render json: manager
      else
        render json: { errors: manager.errors.full_messages }.to_json, status: :unprocessable_entity
      end
    end

    # DELETE /managers/1
    def destroy
      manager = Manager.find(params[:id])
      manager.destroy
      head :no_content
    end

    private
      # Never trust parameters from the scary internet, only allow the white list through.
      def manager_params
        m_params = params.require(:manager).permit(account_attributes:[:name,:email,:password,:password_confirmation])
        m_params[:account_attributes][:uid] = m_params[:account_attributes][:email]
        m_params[:account_attributes][:provider] = "email"
        m_params
      end
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController

  authorize_resource

  swagger_controller :managers, "Managers Account Management"

  swagger_api :index do
    summary "Fetches the information of a single manager account"
    response :ok, "Success", :Manager
    response :forbidden, "You don't have permission"
  end

  # GET /managers
  def index
    cur_acc = current_account
    if cur_acc.is_manager?
      render json: cur_acc.manager
    else
      render json: { errors: "You don't have permission" }, status: 403
    end
  end

  swagger_api :show do
    summary "Fetches the information of a single manager account"
    param :path, :id, :integer, :required, "Manager ID"
    response :ok, "Success", :Manager
    response :forbidden, "You can't access this manager"
  end

  # GET /managers/1
  def show
    manager = Manager.find(params[:id])
    if can? :read, manager
      render json: manager
    else
      render json: { errors: "You can't access this manager" }, status: 403
    end
  end

  swagger_api :create do
    summary "Create a manager account"
    param :form, :account_attributes, :string, :required, "Account object containing params"
    param :form, :name, :string, :optional, "account_attributes[name]"
    param :form, :nickname, :string, :optional, "account_attributes[nickname]"
    param :form, :email, :string, :required, "account_attributes[email]"
    param :form, :birthday, :string, :optional, "account_attributes[birthday]"
    param :form, :phone, :string, :optional, "account_attributes[phone]"
    param :form, :address, :string, :optional, "account_attributes[address]"
    param :form, :password, :string, :required, "account_attributes[password]"
    param :form, :password_confirmation, :string, :required, "account_attributes[password_confirmation]"
    response :created, "Created", :Child
    response :unprocessable_entity, "Unprocessable Entity"
  end

  # POST /managers
  def create
    manager = Manager.create(manager_params)

    if manager.persisted?
      render json: manager, status: 201
    else
      render json: { errors: manager.errors.full_messages }.to_json, status: 422
    end
  end

  swagger_api :update do
    summary "Update information on a Manager Account"
    param :path, :id, :integer, :required, "Manager ID"
    param :form, :account_attributes, :string, :required, "Account object containing params"
    param :form, :name, :string, :optional, "account_attributes[name]"
    param :form, :nickname, :string, :optional, "account_attributes[nickname]"
    param :form, :email, :string, :optional, "account_attributes[email]"
    param :form, :birthday, :string, :optional, "account_attributes[birthday]"
    param :form, :phone, :string, :optional, "account_attributes[phone]"
    param :form, :address, :string, :optional, "account_attributes[address]"
    param :form, :password, :string, :optional, "account_attributes[password]"
    param :form, :password_confirmation, :string, :optional, "account_attributes[password_confirmation]"
    response :ok, "Success", :Child
    response :unprocessable_entity, "Unprocessable Entity"
    response :forbidden, "You can't access this manager"
  end

  # PATCH/PUT /managers/1
  def update
    manager = Manager.find(params[:id])

    if can? :update, manager
      account = manager.account
      if account.update(manager_params[:account_attributes])
        render json: manager
      else
        render json: { errors: manager.errors.full_messages }.to_json, status: :unprocessable_entity
      end
    else
      render json: { errors: "You can't access this manager" }, status: 403
    end
  end

  # DELETE /managers/1
=begin
  def destroy
    manager = Manager.find(params[:id])
    manager.destroy
    head :no_content
  end
=end

  private
    def manager_params
      m_params = params.require(:manager).permit(account_attributes:[:name,:nickname,:email,:birthday,:phone,:address,:password,:password_confirmation])
      m_params[:account_attributes][:uid] = m_params[:account_attributes][:email]
      m_params[:account_attributes][:provider] = "email"
      m_params
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.fields_for :account do |user_form| %>
    <div class="field"><%= user_form.label :uid %><br />
    <%= user_form.text_field :uid %></div>
    <div class="field"><%= user_form.label :name %><br />
    <%= user_form.text_field :name %></div>
    <div class="field"><%= user_form.label :email %><br />
    <%= user_form.email_field :email %></div>
    <div class="field"><%= user_form.label :password %><br />
    <%= user_form.password_field :password %></div>
    <div class="field"><%= user_form.label :password_confirmation %><br />
    <%= user_form.password_field :password_confirmation %></div>
  <% end %>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<h1>Listing managers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>E-Mail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.account.name %></td>
        <td><%= manager.account.email %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %>

app/views/managers/new.html.erb
<h1>New manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>