config/routes.rb
Rails.application.routes.draw do
  

  resources :allowances

  resources :savings

  defaults format: :json do
    constraints format: :json do
      resources :rules

      get "/auth/coinbase", to: "bitcoin_accounts#coinbase_callback"

      mount_devise_token_auth_for 'Account', at: '/auth'
      
      resources :children

      resources :managers

      resources :bitcoin_accounts

      get "/transactions", to: "bitcoin_accounts#transactions"

      post "/payments", to: "bitcoin_accounts#payment"
      
    end
  end
end

app/models/saving.rb
class Saving < ActiveRecord::Base
  belongs_to :child

  def days_left
  	days_left = (Date.today - finish_date).to_i
  	(days_left/365.25).to_i
  end

  def amount_left
  	balance = child.account.bitcoin_account.balance
  	amount_left = value - balance
  	amount_left
  end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController

  authorize_resource

  swagger_controller :savings, "Savings Management"

  swagger_api :index do
    summary "Fetches all savings from a child account"
    response :ok, "Success", :Saving  
  end

  def index
    if can? :read, Saving
      savings = nil
      if current_account.is_child?
        savings = Saving.where(child_id: current_account.child_id)
        #obtem todas as poupanças da child logada
      end
      render json: savings
    else
      render json: { errors: "You can't access savings" }, status: 403
    end
  end

  swagger_api :show do
    summary "Fetches all savings from a child account"
    param :path, :id, :integer, :required, "Child ID"
    response :ok, "Success", :Saving  
  end

  def show
    saving = Saving.find(params[:id])
    if can? :read, saving
      render json: saving
    else
      render json: { errors: "You can't access this saving" }, status: 403
    end
  end

  swagger_api :create do
    summary "Create a saving"
    param :form, :saving, :string, :required, "Saving object containing params"
    param :form, :finish_date, :string, :required, "saving[:finish_date]"
    param :form, :value, :string, :required, "rule[:value]"
    param :form, :child_id, :integer, :required, "rule[:child_id]"
    response :ok, "Success", :Saving
  end

  def create
    if can? :create, Saving
      saving = Saving.create(saving_params)
      if saving.persisted?
        render json: saving
      else
        render json: { errors: saving.errors.full_messages }.to_json, status: 422
      end
    else
      render json: { errors: "You can't create savings" }, status: 403
    end
  end

  swagger_api :Update do
    summary "Update a saving"
    param :form, :saving, :string, :required, "Saving object containing params"
    param :form, :finish_date, :string, :optional, "saving[:finish_date]"
    param :form, :value, :string, :optional, "rule[:value]"
    param :form, :child_id, :integer, :optional, "rule[:child_id]"
    response :ok, "Success", :Saving
  end

  def update
    saving = Saving.find(params[:id])
    if can? :update, saving
      saving.update(saving_params)
      if saving.persisted?
        render json: saving
      else
        render json: { errors: saving.errors.full_messages }.to_json, status: 422
      end
    else
      render json: { errors: "You can't access this saving" }, status: 403
    end
  end

  swagger_api :destroy do
    summary "Delete a saving"
    param :path, :id, :integer, :required, "Child ID"
    response :ok, "Sucess"
  end

  def destroy
    saving = Saving.find(params[:id])
    if can? :destroy, saving
      saving.destroy
      head :no_content
    else
      render json: { errors: "You can't destroy this saving" }, status: 403
    end
  end

  private

    def saving_params
      params.require(:saving).permit(:finish_date, :value, :child_id)
    end
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/views/savings/_form.html.erb
<%= form_for(@saving) do |f| %>
  <% if @saving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saving.errors.count, "error") %> prohibited this saving from being saved:</h2>

      <ul>
      <% @saving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :finish_date %><br>
    <%= f.date_select :finish_date %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :child_id %><br>
    <%= f.text_field :child_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/savings/edit.html.erb
<h1>Editing saving</h1>

<%= render 'form' %>

<%= link_to 'Show', @saving %> |
<%= link_to 'Back', savings_path %>

app/views/savings/index.html.erb
<h1>Listing savings</h1>

<table>
  <thead>
    <tr>
      <th>Finish date</th>
      <th>Value</th>
      <th>Child</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @savings.each do |saving| %>
      <tr>
        <td><%= saving.finish_date %></td>
        <td><%= saving.value %></td>
        <td><%= saving.child %></td>
        <td><%= link_to 'Show', saving %></td>
        <td><%= link_to 'Edit', edit_saving_path(saving) %></td>
        <td><%= link_to 'Destroy', saving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saving', new_saving_path %>

app/views/savings/new.html.erb
<h1>New saving</h1>

<%= render 'form' %>

<%= link_to 'Back', savings_path %>

app/views/savings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Finish date:</strong>
  <%= @saving.finish_date %>
</p>

<p>
  <strong>Value:</strong>
  <%= @saving.value %>
</p>

<p>
  <strong>Child:</strong>
  <%= @saving.child %>
</p>

<%= link_to 'Edit', edit_saving_path(@saving) %> |
<%= link_to 'Back', savings_path %>