config/routes.rb
Rails.application.routes.draw do
  

  resources :allowances

  resources :savings

  defaults format: :json do
    constraints format: :json do
      resources :rules

      get "/auth/coinbase", to: "bitcoin_accounts#coinbase_callback"

      mount_devise_token_auth_for 'Account', at: '/auth'
      
      resources :children

      resources :managers

      resources :bitcoin_accounts

      get "/transactions", to: "bitcoin_accounts#transactions"

      post "/payments", to: "bitcoin_accounts#payment"
      
    end
  end
end

app/models/allowance.rb
class Allowance < ActiveRecord::Base
  belongs_to :child

  validates_inclusion_of :period, :in => ["day", "week", "month", "year"]
end

app/controllers/allowances_controller.rb
class AllowancesController < ApplicationController

  authorize_resource

  def index
    if can? :read, Allowance
      allowances = nil
      if current_account.is_child?
        allowances = Allowance.where(child_id: current_account.child_id
        #obtem todas as semanadas da child logada
      end
      render json: allowances
    else
      render json: { errors: "You can't access allowances" }, status: 403
    end
  end

  def show
    allowance = Allowance.find(params[:id])
    if can? :read, allowance
      render json: allowance
    else
      render json: { errors: "You can't access this allowance" }, status: 403
    end
  end

  def create
    if can? :create, Allowance
      allowance = Allowance.create(allowance_params)
      if allowance.persisted?
        render json: allowance
      else
        render json: { errors: allowance.errors.full_messages }.to_json, status: 422
      end
    else
      render json: { errors: "You can't create allowances" }, status: 403
    end
  end

  def update
    allowance = Allowance.find(params[:id])
    if can? :update, allowance
      allowance.update(allowance_params)
      if allowance.persisted?
        render json: allowance
      else
        render json: { errors: allowance.errors.full_messages }.to_json, status: 422
      end
    else
      render json: { errors: "You can't access this allowance" }, status: 403
    end
  end

  def destroy
    allowance = Allowance.find(params[:id])
    if can? :destroy, allowance
      allowance.destroy
      head :no_content
    else
      render json: { errors: "You can't destroy this allowance" }, status: 403
    end
  end

  private
    def allowance_params
      params.require(:allowance).permit(:amount, :period, :child_id)
    end
end

app/helpers/allowances_helper.rb
module AllowancesHelper
end

app/views/allowances/_form.html.erb
<%= form_for(@allowance) do |f| %>
  <% if @allowance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allowance.errors.count, "error") %> prohibited this allowance from being saved:</h2>

      <ul>
      <% @allowance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.text_field :period %>
  </div>
  <div class="field">
    <%= f.label :child_id %><br>
    <%= f.text_field :child_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allowances/edit.html.erb
<h1>Editing allowance</h1>

<%= render 'form' %>

<%= link_to 'Show', @allowance %> |
<%= link_to 'Back', allowances_path %>

app/views/allowances/index.html.erb
<h1>Listing allowances</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Period</th>
      <th>Child</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @allowances.each do |allowance| %>
      <tr>
        <td><%= allowance.amount %></td>
        <td><%= allowance.period %></td>
        <td><%= allowance.child %></td>
        <td><%= link_to 'Show', allowance %></td>
        <td><%= link_to 'Edit', edit_allowance_path(allowance) %></td>
        <td><%= link_to 'Destroy', allowance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allowance', new_allowance_path %>

app/views/allowances/new.html.erb
<h1>New allowance</h1>

<%= render 'form' %>

<%= link_to 'Back', allowances_path %>

app/views/allowances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @allowance.amount %>
</p>

<p>
  <strong>Period:</strong>
  <%= @allowance.period %>
</p>

<p>
  <strong>Child:</strong>
  <%= @allowance.child %>
</p>

<%= link_to 'Edit', edit_allowance_path(@allowance) %> |
<%= link_to 'Back', allowances_path %>